#################
#JoinTitle
#By MilkAndCookiz
#Version: 1.0.1
#A join title plugin for your server, configurable & functional.
#If you have any suggest, you can contact me on Twitter ! @MilkAndCookiz
#################

#main_title: Change the big title here, for example you can put your server name here.
main_title: "§l§9Your Server§r"

#down_title: Change the little title here, for example you can put a welcome message here.
down_title: "§6§ki§9i§ai§r §7§o#Welcome !§r §a§ki§9i§6i§r"

#time_title: Change the appearance time of the title here. 20 = 1 sec.
time_title: 60
